# Generated by Django 3.0.7 on 2020-06-06 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30, verbose_name='دسته بندی')),
                ('cat_slug', models.SlugField(verbose_name='لینک دسته بندی')),
            ],
        ),
        migrations.CreateModel(
            name='addAds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=52, verbose_name='عنوان آگهی')),
                ('body', models.TextField(verbose_name='توضیحات آگهی')),
                ('price', models.BigIntegerField(verbose_name='قیمت')),
                ('Adspic', models.ImageField(upload_to='upload/ads_pic', verbose_name='تصویر آگهی')),
                ('category', models.ManyToManyField(to='web.category', verbose_name='دسته بندی')),
            ],
        ),
    ]
