# Generated by Django 3.0.7 on 2020-06-09 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addads',
            name='status',
            field=models.CharField(choices=[('d', 'پیش\u200cنویس'), ('p', 'منتشر شده')], default=1, max_length=1, verbose_name='وضعیت'),
            preserve_default=False,
        ),
    ]
