# Generated by Django 3.0.7 on 2020-06-09 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0002_addads_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cty', models.CharField(max_length=30, verbose_name='استان')),
            ],
        ),
        migrations.AlterModelOptions(
            name='addads',
            options={'verbose_name': 'آگهی', 'verbose_name_plural': 'آگهی ها'},
        ),
        migrations.AddField(
            model_name='addads',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='addads',
            name='status',
            field=models.CharField(choices=[('d', 'درانتظار تایید'), ('f', 'پیش نویس'), ('p', 'منتشر شده')], max_length=1, verbose_name='وضعیت'),
        ),
    ]
