# Generated by Django 3.0.7 on 2020-06-09 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20200610_0251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AddField(
            model_name='addads',
            name='city',
            field=models.ManyToManyField(to='web.City', verbose_name='استان'),
        ),
    ]
