# Generated by Django 3.0.7 on 2020-06-09 22:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20200610_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addads',
            name='status',
            field=models.CharField(choices=[('f', 'پیش نویس'), ('d', 'درانتظار تایید'), ('p', 'منتشر شده'), ('v', 'آگهی ویژه')], max_length=1, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='addads',
            name='timepub',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار'),
        ),
    ]
