# Generated by Django 3.0.7 on 2020-06-18 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20200610_0308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'استان', 'verbose_name_plural': 'استان ها'},
        ),
    ]
