# Generated by Django 3.0.7 on 2020-06-27 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20200618_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='addads',
            name='slug',
            field=models.SlugField(default=1, max_length=100, unique=True, verbose_name='آدرس مقاله'),
            preserve_default=False,
        ),
    ]
